# Generated by Django 4.1.3 on 2022-11-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='ip',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.TimeField(null=True, unique=True),
        ),
    ]
