# Generated by Django 4.1.3 on 2022-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityair', '0002_city_ip_city_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ip',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
